# This file was generated by GoReleaser. DO NOT EDIT.
class GoYoutubeAccruedRoyalties < Formula
  desc "Command line tool for extracting records from YouTube accrued publishing royalties."
  homepage "https://github.com/daniel-zahariev/go-youtube-accrued-royalties"
  url "https://github.com/daniel-zahariev/go-youtube-accrued-royalties/releases/download/v0.0.2/go-youtube-accrued-royalties_0.0.2_darwin_amd64.tar.gz"
  version "0.0.2"
  sha256 "e8e2ed1afba27796b747e91e07ac56436d58fb3eff4a0de136142a2f035685f8"

  def install
    bin.install "go-youtube-accrued-royalties"
  end
end
